name: Docker
on:
  workflow_dispatch:
  push:
    branches: [main, dev, test]
    tags: ["*"]
permissions:
  contents: read
  packages: write
jobs:
  docker:
    uses: hanzoai/.github/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/hanzoai/sentry
      dockerfile: self-hosted/Dockerfile
      pre-build-command: |
        pip install wheel setuptools
        pip install -r requirements-base.txt
        python setup.py bdist_wheel
        mkdir -p dist
        pip freeze > dist/requirements-frozen.txt
        yarn install --frozen-lockfile
        yarn build
    secrets: inherit
